# build an executable named myprog from myprog.c
all: Minimum_Spanning_Tree.c 
	gcc -g -Wall -Wextra -pedantic -std=c99 -o Minimum_Spanning_Tree Minimum_Spanning_Tree.c

clean: 
	$(RM) Minimum_Spanning_Tree
